version: '3'
services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=your-production-secret-key
    volumes:
      - ./app/uploads:/app/app/uploads 